// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/proto/grpc_task/v1/task.proto

package grpctaskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskStatus 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 1
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 2
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_COMPLETED",
		2: "TASK_STATUS_FAILED",
		3: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_COMPLETED":   1,
		"TASK_STATUS_FAILED":      2,
		"TASK_STATUS_CANCELLED":   3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_grpc_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_api_proto_grpc_task_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{0}
}

// HealthStatus 健康状态枚举
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
		3: "HEALTH_STATUS_DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
		"HEALTH_STATUS_DEGRADED":    3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_grpc_task_v1_task_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_api_proto_grpc_task_v1_task_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{1}
}

// ExecuteTaskRequest 任务执行请求
type ExecuteTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id 任务唯一标识
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// task_type 任务类型，对应 payload 中的 method
	TaskType string `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	// payload 任务数据
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// metadata 元数据
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// options 执行选项
	Options       *ExecutionOptions `protobuf:"bytes,5,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ExecuteTaskRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteTaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteTaskRequest) GetOptions() *ExecutionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// ExecutionOptions 执行选项
type ExecutionOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeout_ms 超时时间（毫秒）
	TimeoutMs int64 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// enable_progress 是否启用进度报告
	EnableProgress bool `protobuf:"varint,2,opt,name=enable_progress,json=enableProgress,proto3" json:"enable_progress,omitempty"`
	// progress_interval_ms 进度报告间隔（毫秒）
	ProgressIntervalMs int32 `protobuf:"varint,3,opt,name=progress_interval_ms,json=progressIntervalMs,proto3" json:"progress_interval_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecutionOptions) Reset() {
	*x = ExecutionOptions{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionOptions) ProtoMessage() {}

func (x *ExecutionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionOptions.ProtoReflect.Descriptor instead.
func (*ExecutionOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionOptions) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecutionOptions) GetEnableProgress() bool {
	if x != nil {
		return x.EnableProgress
	}
	return false
}

func (x *ExecutionOptions) GetProgressIntervalMs() int32 {
	if x != nil {
		return x.ProgressIntervalMs
	}
	return 0
}

// ExecuteTaskResponse 任务执行响应（流式）
type ExecuteTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExecuteTaskResponse_Progress
	//	*ExecuteTaskResponse_Result
	//	*ExecuteTaskResponse_Error
	Response      isExecuteTaskResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteTaskResponse) GetResponse() isExecuteTaskResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExecuteTaskResponse) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ExecuteTaskResponse) GetResult() *TaskResult {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ExecuteTaskResponse) GetError() *ErrorDetail {
	if x != nil {
		if x, ok := x.Response.(*ExecuteTaskResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isExecuteTaskResponse_Response interface {
	isExecuteTaskResponse_Response()
}

type ExecuteTaskResponse_Progress struct {
	// progress 任务进度
	Progress *Progress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type ExecuteTaskResponse_Result struct {
	// result 任务结果
	Result *TaskResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type ExecuteTaskResponse_Error struct {
	// error 错误信息
	Error *ErrorDetail `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ExecuteTaskResponse_Progress) isExecuteTaskResponse_Response() {}

func (*ExecuteTaskResponse_Result) isExecuteTaskResponse_Response() {}

func (*ExecuteTaskResponse_Error) isExecuteTaskResponse_Response() {}

// Progress 任务进度
type Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// percentage 完成百分比 (0-100)
	Percentage int32 `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	// stage 当前阶段
	Stage string `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	// message 进度消息
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp_ms 时间戳（毫秒）
	TimestampMs int64 `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// metadata 额外元数据
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *Progress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Progress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *Progress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Progress) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Progress) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskResult 任务结果
type TaskResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// status 任务状态
	Status TaskStatus `protobuf:"varint,2,opt,name=status,proto3,enum=grpc_task.v1.TaskStatus" json:"status,omitempty"`
	// data 结果数据
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// duration_ms 执行耗时（毫秒）
	DurationMs    int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ErrorDetail 错误详情
type ErrorDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// code 错误码
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// message 错误消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// retryable 是否可重试
	Retryable bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// retry_after_seconds 建议重试等待时间
	RetryAfterSeconds int32 `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorDetail) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

// CancelTaskRequest 取消任务请求
type CancelTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id 要取消的任务ID
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// reason 取消原因
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelTaskResponse 取消任务响应
type CancelTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message 响应消息
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service_name 服务名称（可选）
	ServiceName   string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 健康状态
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=grpc_task.v1.HealthStatus" json:"status,omitempty"`
	// message 状态消息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// details 详细信息
	Details       map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_grpc_task_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_grpc_task_v1_task_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_proto_grpc_task_v1_task_proto protoreflect.FileDescriptor

const file_api_proto_grpc_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"!api/proto/grpc_task/v1/task.proto\x12\fgrpc_task.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xc0\x02\n" +
	"\x12ExecuteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..grpc_task.v1.ExecuteTaskRequest.MetadataEntryR\bmetadata\x128\n" +
	"\aoptions\x18\x05 \x01(\v2\x1e.grpc_task.v1.ExecutionOptionsR\aoptions\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x10ExecutionOptions\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\x03R\ttimeoutMs\x12'\n" +
	"\x0fenable_progress\x18\x02 \x01(\bR\x0eenableProgress\x120\n" +
	"\x14progress_interval_ms\x18\x03 \x01(\x05R\x12progressIntervalMs\"\xbe\x01\n" +
	"\x13ExecuteTaskResponse\x124\n" +
	"\bprogress\x18\x01 \x01(\v2\x16.grpc_task.v1.ProgressH\x00R\bprogress\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x18.grpc_task.v1.TaskResultH\x00R\x06result\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x19.grpc_task.v1.ErrorDetailH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x95\x02\n" +
	"\bProgress\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.grpc_task.v1.Progress.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.grpc_task.v1.TaskStatusR\x06status\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"\x89\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\x05R\x11retryAfterSeconds\"D\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xe9\x01\n" +
	"\x13HealthCheckResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.grpc_task.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\adetails\x18\x03 \x03(\v2..grpc_task.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*w\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x03*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x032\x90\x02\n" +
	"\x13TaskExecutorService\x12T\n" +
	"\vExecuteTask\x12 .grpc_task.v1.ExecuteTaskRequest\x1a!.grpc_task.v1.ExecuteTaskResponse0\x01\x12O\n" +
	"\n" +
	"CancelTask\x12\x1f.grpc_task.v1.CancelTaskRequest\x1a .grpc_task.v1.CancelTaskResponse\x12R\n" +
	"\vHealthCheck\x12 .grpc_task.v1.HealthCheckRequest\x1a!.grpc_task.v1.HealthCheckResponseB@Z>github.com/Aixtrade/TaskFlow/api/proto/grpc_task/v1;grpctaskv1b\x06proto3"

var (
	file_api_proto_grpc_task_v1_task_proto_rawDescOnce sync.Once
	file_api_proto_grpc_task_v1_task_proto_rawDescData []byte
)

func file_api_proto_grpc_task_v1_task_proto_rawDescGZIP() []byte {
	file_api_proto_grpc_task_v1_task_proto_rawDescOnce.Do(func() {
		file_api_proto_grpc_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_grpc_task_v1_task_proto_rawDesc), len(file_api_proto_grpc_task_v1_task_proto_rawDesc)))
	})
	return file_api_proto_grpc_task_v1_task_proto_rawDescData
}

var file_api_proto_grpc_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_grpc_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_grpc_task_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),             // 0: grpc_task.v1.TaskStatus
	(HealthStatus)(0),           // 1: grpc_task.v1.HealthStatus
	(*ExecuteTaskRequest)(nil),  // 2: grpc_task.v1.ExecuteTaskRequest
	(*ExecutionOptions)(nil),    // 3: grpc_task.v1.ExecutionOptions
	(*ExecuteTaskResponse)(nil), // 4: grpc_task.v1.ExecuteTaskResponse
	(*Progress)(nil),            // 5: grpc_task.v1.Progress
	(*TaskResult)(nil),          // 6: grpc_task.v1.TaskResult
	(*ErrorDetail)(nil),         // 7: grpc_task.v1.ErrorDetail
	(*CancelTaskRequest)(nil),   // 8: grpc_task.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),  // 9: grpc_task.v1.CancelTaskResponse
	(*HealthCheckRequest)(nil),  // 10: grpc_task.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 11: grpc_task.v1.HealthCheckResponse
	nil,                         // 12: grpc_task.v1.ExecuteTaskRequest.MetadataEntry
	nil,                         // 13: grpc_task.v1.Progress.MetadataEntry
	nil,                         // 14: grpc_task.v1.HealthCheckResponse.DetailsEntry
	(*structpb.Struct)(nil),     // 15: google.protobuf.Struct
}
var file_api_proto_grpc_task_v1_task_proto_depIdxs = []int32{
	15, // 0: grpc_task.v1.ExecuteTaskRequest.payload:type_name -> google.protobuf.Struct
	12, // 1: grpc_task.v1.ExecuteTaskRequest.metadata:type_name -> grpc_task.v1.ExecuteTaskRequest.MetadataEntry
	3,  // 2: grpc_task.v1.ExecuteTaskRequest.options:type_name -> grpc_task.v1.ExecutionOptions
	5,  // 3: grpc_task.v1.ExecuteTaskResponse.progress:type_name -> grpc_task.v1.Progress
	6,  // 4: grpc_task.v1.ExecuteTaskResponse.result:type_name -> grpc_task.v1.TaskResult
	7,  // 5: grpc_task.v1.ExecuteTaskResponse.error:type_name -> grpc_task.v1.ErrorDetail
	13, // 6: grpc_task.v1.Progress.metadata:type_name -> grpc_task.v1.Progress.MetadataEntry
	0,  // 7: grpc_task.v1.TaskResult.status:type_name -> grpc_task.v1.TaskStatus
	15, // 8: grpc_task.v1.TaskResult.data:type_name -> google.protobuf.Struct
	1,  // 9: grpc_task.v1.HealthCheckResponse.status:type_name -> grpc_task.v1.HealthStatus
	14, // 10: grpc_task.v1.HealthCheckResponse.details:type_name -> grpc_task.v1.HealthCheckResponse.DetailsEntry
	2,  // 11: grpc_task.v1.TaskExecutorService.ExecuteTask:input_type -> grpc_task.v1.ExecuteTaskRequest
	8,  // 12: grpc_task.v1.TaskExecutorService.CancelTask:input_type -> grpc_task.v1.CancelTaskRequest
	10, // 13: grpc_task.v1.TaskExecutorService.HealthCheck:input_type -> grpc_task.v1.HealthCheckRequest
	4,  // 14: grpc_task.v1.TaskExecutorService.ExecuteTask:output_type -> grpc_task.v1.ExecuteTaskResponse
	9,  // 15: grpc_task.v1.TaskExecutorService.CancelTask:output_type -> grpc_task.v1.CancelTaskResponse
	11, // 16: grpc_task.v1.TaskExecutorService.HealthCheck:output_type -> grpc_task.v1.HealthCheckResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_grpc_task_v1_task_proto_init() }
func file_api_proto_grpc_task_v1_task_proto_init() {
	if File_api_proto_grpc_task_v1_task_proto != nil {
		return
	}
	file_api_proto_grpc_task_v1_task_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecuteTaskResponse_Progress)(nil),
		(*ExecuteTaskResponse_Result)(nil),
		(*ExecuteTaskResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_grpc_task_v1_task_proto_rawDesc), len(file_api_proto_grpc_task_v1_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_grpc_task_v1_task_proto_goTypes,
		DependencyIndexes: file_api_proto_grpc_task_v1_task_proto_depIdxs,
		EnumInfos:         file_api_proto_grpc_task_v1_task_proto_enumTypes,
		MessageInfos:      file_api_proto_grpc_task_v1_task_proto_msgTypes,
	}.Build()
	File_api_proto_grpc_task_v1_task_proto = out.File
	file_api_proto_grpc_task_v1_task_proto_goTypes = nil
	file_api_proto_grpc_task_v1_task_proto_depIdxs = nil
}
