// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: api/proto/grpc_task/v1/task.proto

package grpctaskv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskExecutorService_ExecuteTask_FullMethodName = "/grpc_task.v1.TaskExecutorService/ExecuteTask"
	TaskExecutorService_CancelTask_FullMethodName  = "/grpc_task.v1.TaskExecutorService/CancelTask"
	TaskExecutorService_HealthCheck_FullMethodName = "/grpc_task.v1.TaskExecutorService/HealthCheck"
)

// TaskExecutorServiceClient is the client API for TaskExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskExecutorService 定义了通用的流式任务执行接口
// 可以被任何语言（Python、Java、Node.js、Rust 等）实现
type TaskExecutorServiceClient interface {
	// ExecuteTask 执行任务并通过流返回进度和结果
	ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteTaskResponse], error)
	// CancelTask 取消正在执行的任务
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// HealthCheck 检查服务健康状态
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type taskExecutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecutorServiceClient(cc grpc.ClientConnInterface) TaskExecutorServiceClient {
	return &taskExecutorServiceClient{cc}
}

func (c *taskExecutorServiceClient) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteTaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskExecutorService_ServiceDesc.Streams[0], TaskExecutorService_ExecuteTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteTaskRequest, ExecuteTaskResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutorService_ExecuteTaskClient = grpc.ServerStreamingClient[ExecuteTaskResponse]

func (c *taskExecutorServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, TaskExecutorService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutorServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TaskExecutorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskExecutorServiceServer is the server API for TaskExecutorService service.
// All implementations must embed UnimplementedTaskExecutorServiceServer
// for forward compatibility.
//
// TaskExecutorService 定义了通用的流式任务执行接口
// 可以被任何语言（Python、Java、Node.js、Rust 等）实现
type TaskExecutorServiceServer interface {
	// ExecuteTask 执行任务并通过流返回进度和结果
	ExecuteTask(*ExecuteTaskRequest, grpc.ServerStreamingServer[ExecuteTaskResponse]) error
	// CancelTask 取消正在执行的任务
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// HealthCheck 检查服务健康状态
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedTaskExecutorServiceServer()
}

// UnimplementedTaskExecutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecutorServiceServer struct{}

func (UnimplementedTaskExecutorServiceServer) ExecuteTask(*ExecuteTaskRequest, grpc.ServerStreamingServer[ExecuteTaskResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedTaskExecutorServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTaskExecutorServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTaskExecutorServiceServer) mustEmbedUnimplementedTaskExecutorServiceServer() {}
func (UnimplementedTaskExecutorServiceServer) testEmbeddedByValue()                             {}

// UnsafeTaskExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecutorServiceServer will
// result in compilation errors.
type UnsafeTaskExecutorServiceServer interface {
	mustEmbedUnimplementedTaskExecutorServiceServer()
}

func RegisterTaskExecutorServiceServer(s grpc.ServiceRegistrar, srv TaskExecutorServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskExecutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecutorService_ServiceDesc, srv)
}

func _TaskExecutorService_ExecuteTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskExecutorServiceServer).ExecuteTask(m, &grpc.GenericServerStream[ExecuteTaskRequest, ExecuteTaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutorService_ExecuteTaskServer = grpc.ServerStreamingServer[ExecuteTaskResponse]

func _TaskExecutorService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutorService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskExecutorService_ServiceDesc is the grpc.ServiceDesc for TaskExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_task.v1.TaskExecutorService",
	HandlerType: (*TaskExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelTask",
			Handler:    _TaskExecutorService_CancelTask_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TaskExecutorService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteTask",
			Handler:       _TaskExecutorService_ExecuteTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/grpc_task/v1/task.proto",
}
